-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Treeni CASCADE;
DROP TABLE IF EXISTS Liike CASCADE;
DROP TABLE IF EXISTS Voimalaji CASCADE;
DROP TABLE IF EXISTS Treeniliike CASCADE;
DROP TABLE IF EXISTS Voimatreeni CASCADE;